# Generated by Django 3.1.1 on 2020-09-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_auto_20200914_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
