# Generated by Django 3.1.1 on 2020-09-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_auto_20200914_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='cover_pic',
            field=models.ImageField(blank=True, upload_to='cover_pic'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile_pic'),
        ),
    ]
