# Generated by Django 3.1.1 on 2020-09-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_auto_20200914_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='clubs',
            field=models.CharField(blank=True, choices=[('Encore', 'Encore'), ('Coding Club', 'Coding Club'), ('Masquerade', 'Masquerade'), ('Mod5', 'Mod5'), ('Shades', 'Shades'), ('Arcadia', 'Arcadia'), ('DOT', 'DOT'), ('Enigma', 'Enigma'), ('Sports Committee', 'Sports Committee'), ('Cultural Committee', 'Cultural Committee'), ('Technical Committee', 'Technical Committee'), ('Literature Committee', 'Literature Committee')], max_length=300),
        ),
    ]
